version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - sudo pip install boto3
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_1.5.7_linux_amd64.zip
      - yum update
      - yum -y install  curl jq
      - echo "Prepare terraform file"
      - cd workshop/eks-spark-airflow
      - echo "terraform { " >> backend.tf
      - echo "   backend \"s3\" { " >> backend.tf
      - echo "   bucket = \"$s3statebucket\"" >> backend.tf
      - echo "   key    = \"$stackname/terraform.tfstate\"" >> backend.tf
      - echo "   region = \"$region\"" >> backend.tf
      - echo "  }" >> backend.tf
      - echo "}" >> backend.tf
      - cat backend.tf
      - terraform init
  build:
    commands:
      - terraform plan
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
